### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by tomking** [frederikgram/resume#1]
Hey just wanted to give you a heads up, under "Custom Programming Language" at the bottom of the pdf, programming is misspelled "programmoing"

**Comment by frederikgram** [comment]
Ehm, hello Thomas.  I'm not quite sure how you were notified of this, but thank you nevertheless. This is purely a draft so I'm not too worried

**Comment by tomking** [comment]
👍🏻I think it popped up in my feed because I follow you. Just noticed the misspell and thought I would let you know in case it mattered, have a good one!
